#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# use UP and DOWN to cycle through history substring matches
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Customize to your needs...
